import {organization} from './organization.js';

// Все ФИО вымышлены; записи предназначены только для демонстрации.
export const employees={kind:'demo',version:1,employees:[
 {id:'emp-001',fullName:'Марк Сергеев',position:'Генеральный директор',unitId:'leadership',education:'Высшее, управление',yearsExperience:16,certifications:['MBA'],competencies:['Стратегическое управление','Организационное развитие'],authorities:['Утверждение внутренних документов','Назначение руководителей'],functions:['Утверждение стратегии','Постановка целей подразделениям'],responsibilities:['Результаты деятельности компании','Контроль исполнения стратегии']},
 {id:'emp-002',fullName:'Алина Миронова',position:'Руководитель департамента ИБ',unitId:'security',education:'Высшее, информационная безопасность',yearsExperience:11,certifications:['CISSP'],competencies:['Управление рисками ИБ','Координация реагирования'],authorities:['Запрос сведений об инцидентах','Инициирование проверки ИБ'],functions:['Разработка требований ИБ','Координация реагирования на инциденты'],responsibilities:['Контроль рисков ИБ','Планирование работы департамента']},
 {id:'emp-003',fullName:'Алексей Иванов',position:'Аналитик ИБ',unitId:'security',education:'Высшее, компьютерные науки',yearsExperience:4,certifications:['Security+'],competencies:['Анализ событий ИБ','Разбор инцидентов'],authorities:['Просмотр журналов событий','Анализ данных об инцидентах'],functions:['Мониторинг событий ИБ','Анализ инцидентов'],responsibilities:['Своевременная эскалация подозрительных событий','Точность аналитических выводов']},
 {id:'emp-004',fullName:'Динара Садыкова',position:'Специалист ИБ',unitId:'security',education:'Высшее, информационная безопасность',yearsExperience:3,certifications:['ISO/IEC 27001 Foundation'],competencies:['Управление доступом','Разработка инструкций ИБ'],authorities:['Проверка заявок на доступ','Запрос сведений о соблюдении процедур'],functions:['Проверка доступа','Подготовка инструкций ИБ'],responsibilities:['Актуальность инструкций','Учёт замечаний по доступу']},
 {id:'emp-005',fullName:'Тимур Волков',position:'Руководитель ИТ-департамента',unitId:'it',education:'Высшее, информационные системы',yearsExperience:12,certifications:['ITIL Foundation'],competencies:['Управление ИТ-сервисами','Планирование изменений'],authorities:['Согласование технических работ','Распределение задач ИТ'],functions:['Управление эксплуатацией ИТ','Планирование изменений'],responsibilities:['Доступность сервисов','Качество технических работ']},
 {id:'emp-006',fullName:'Роман Беляев',position:'Системный администратор',unitId:'it',education:'Высшее, вычислительная техника',yearsExperience:6,certifications:['Linux Foundation Certified System Administrator'],competencies:['Администрирование серверов','Резервное копирование'],authorities:['Администрирование серверов в рамках роли','Выполнение утверждённых заявок'],functions:['Обслуживание серверов','Проверка резервных копий'],responsibilities:['Работоспособность серверов','Учёт выполненных изменений']},
 {id:'emp-007',fullName:'Елена Ким',position:'Сетевой инженер',unitId:'it',education:'Высшее, телекоммуникации',yearsExperience:5,certifications:['CCNA'],competencies:['Маршрутизация','Мониторинг сети'],authorities:['Настройка сетевого оборудования по заявкам','Просмотр технических метрик сети'],functions:['Эксплуатация сети','Диагностика сетевых сбоев'],responsibilities:['Доступность сети','Документирование сетевых изменений']},
 {id:'emp-008',fullName:'Виктор Орлов',position:'Руководитель финансового департамента',unitId:'finance',education:'Высшее, финансы',yearsExperience:13,certifications:['ACCA Fundamentals'],competencies:['Бюджетирование','Финансовое планирование'],authorities:['Запрос финансовых планов','Согласование бюджета'],functions:['Формирование бюджета','Контроль финансовых процедур'],responsibilities:['Достоверность бюджета','Соблюдение финансовых правил']},
 {id:'emp-009',fullName:'София Назарова',position:'Финансовый аналитик',unitId:'finance',education:'Высшее, экономика',yearsExperience:4,certifications:['CFA Level I'],competencies:['Анализ расходов','Финансовое моделирование'],authorities:['Запрос бюджетных данных','Подготовка аналитических отчётов'],functions:['Анализ исполнения бюджета','Подготовка платёжных документов'],responsibilities:['Точность расчётов','Своевременность отчётности']},
 {id:'emp-010',fullName:'Павел Громов',position:'Руководитель юридического департамента',unitId:'legal',education:'Высшее, право',yearsExperience:14,certifications:[],competencies:['Договорное право','Правовая экспертиза'],authorities:['Запрос проектов договоров','Утверждение правовых заключений'],functions:['Организация правовой экспертизы','Консультирование руководства'],responsibilities:['Качество правовых заключений','Сопровождение договоров']},
 {id:'emp-011',fullName:'Лейла Каримова',position:'Юрист',unitId:'legal',education:'Высшее, право',yearsExperience:5,certifications:[],competencies:['Анализ договоров','Подготовка заключений'],authorities:['Запрос материалов договора','Подготовка правового заключения'],functions:['Проверка проектов договоров','Подготовка замечаний'],responsibilities:['Корректность замечаний','Соблюдение сроков экспертизы']},
 {id:'emp-012',fullName:'Наталья Морозова',position:'Руководитель HR',unitId:'hr',education:'Высшее, управление персоналом',yearsExperience:10,certifications:['SHRM-CP'],competencies:['Управление персоналом','Планирование обучения'],authorities:['Организация подбора','Запрос кадровых данных'],functions:['Координация подбора','Планирование обучения'],responsibilities:['Актуальность кадровых процессов','Развитие персонала']},
 {id:'emp-013',fullName:'Илья Соколов',position:'Специалист по персоналу',unitId:'hr',education:'Высшее, управление персоналом',yearsExperience:3,certifications:[],competencies:['Кадровый учёт','Организация обучения'],authorities:['Обработка кадровых сведений в рамках роли','Подготовка материалов обучения'],functions:['Ведение кадрового учёта','Организация обучения'],responsibilities:['Точность кадровых записей','Соблюдение сроков оформления']},
 {id:'emp-014',fullName:'Ольга Федорова',position:'Руководитель внутреннего аудита',unitId:'audit',education:'Высшее, аудит и финансы',yearsExperience:12,certifications:['CIA'],competencies:['Планирование аудита','Оценка контроля'],authorities:['Запрос документов по плану проверки','Представление результатов руководству'],functions:['Планирование проверок','Подготовка независимых рекомендаций'],responsibilities:['Объективность выводов','Качество плана проверок']},
 {id:'emp-015',fullName:'Арман Тулеев',position:'Внутренний аудитор',unitId:'audit',education:'Высшее, экономика',yearsExperience:6,certifications:['CIA Part 1'],competencies:['Сбор аудиторских доказательств','Оценка процессов'],authorities:['Изучение материалов утверждённой проверки','Запрос разъяснений'],functions:['Проведение внутренних проверок','Подготовка рабочих документов'],responsibilities:['Достоверность доказательств','Сохранность материалов проверки']}
]};

export function validateEmployees(data,model=organization){
 if(!data||!Array.isArray(data.employees))return ['Отсутствует список сотрудников'];
 const errors=[],ids=new Set(),units=new Map(model.units.map(u=>[u.id,u]));
 for(const e of data.employees){
  if(ids.has(e.id))errors.push(`${e.id}: повторяется ID`);ids.add(e.id);
  for(const key of ['id','fullName','position','unitId','education'])if(typeof e[key]!=='string'||!e[key].trim())errors.push(`${e.id}: не заполнено ${key}`);
  if(!Number.isInteger(e.yearsExperience)||e.yearsExperience<0||e.yearsExperience>60)errors.push(`${e.id}: некорректный стаж`);
  for(const key of ['certifications','competencies','authorities','functions','responsibilities'])if(!Array.isArray(e[key])||(key!=='certifications'&&!e[key].length))errors.push(`${e.id}: некорректно поле ${key}`);
  const unit=units.get(e.unitId);if(!unit)errors.push(`${e.id}: неизвестное подразделение`);
  else if(!unit.positions.includes(e.position))errors.push(`${e.id}: должность не принадлежит подразделению`);
 }
 for(const unit of model.units){const heads=data.employees.filter(e=>e.unitId===unit.id&&e.position===unit.head);if(heads.length!==1)errors.push(`${unit.id}: должен быть ровно один руководитель`);}
 return errors;
}
